// <auto-generated />
using System;
using Group3Flight.Models.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Group3Flight.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20260414185153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("Group3Flight.Models.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirlineId");

                    b.ToTable("Airline");

                    b.HasData(
                        new
                        {
                            AirlineId = 11,
                            ImageName = "SpiritAirlines.png",
                            Name = "Spirit Airlines"
                        },
                        new
                        {
                            AirlineId = 12,
                            ImageName = "FrontierAirlines.png",
                            Name = "Frontier Airlines"
                        },
                        new
                        {
                            AirlineId = 13,
                            ImageName = "HawaiianAirlines.png",
                            Name = "Hawaiian Airlines"
                        },
                        new
                        {
                            AirlineId = 14,
                            ImageName = "AllegiantAir.png",
                            Name = "Allegiant Air"
                        },
                        new
                        {
                            AirlineId = 15,
                            ImageName = "SunCountry.png",
                            Name = "Sun Country Airlines"
                        },
                        new
                        {
                            AirlineId = 16,
                            ImageName = "SilverAirways.png",
                            Name = "Silver Airways"
                        });
                });

            modelBuilder.Entity("Group3Flight.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CabinType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Emission")
                        .HasColumnType("REAL");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flight");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AircraftType = "Airbus A321",
                            AirlineId = 11,
                            ArrivalTime = new TimeSpan(0, 9, 30, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 7, 15, 0, 0),
                            Emission = 200.30000000000001,
                            FlightCode = "NK601",
                            From = "Miami",
                            Price = 150.00m,
                            To = "Houston"
                        },
                        new
                        {
                            FlightId = 2,
                            AircraftType = "Airbus A320neo",
                            AirlineId = 12,
                            ArrivalTime = new TimeSpan(0, 20, 10, 0, 0),
                            CabinType = "Basic Economy",
                            Date = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 12, 45, 0, 0),
                            Emission = 300.5,
                            FlightCode = "FA123",
                            From = "Las Vegas",
                            Price = 275.00m,
                            To = "Orlando"
                        },
                        new
                        {
                            FlightId = 3,
                            AircraftType = "Airbus A330",
                            AirlineId = 13,
                            ArrivalTime = new TimeSpan(0, 23, 30, 0, 0),
                            CabinType = "Business",
                            Date = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 16, 0, 0, 0),
                            Emission = 410.80000000000001,
                            FlightCode = "HA789",
                            From = "Honolulu",
                            Price = 680.00m,
                            To = "San Diego"
                        },
                        new
                        {
                            FlightId = 4,
                            AircraftType = "Boeing 737 MAX",
                            AirlineId = 14,
                            ArrivalTime = new TimeSpan(0, 12, 55, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 10, 20, 0, 0),
                            Emission = 220.40000000000001,
                            FlightCode = "GN450",
                            From = "Nashville",
                            Price = 195.00m,
                            To = "Phoenix"
                        },
                        new
                        {
                            FlightId = 5,
                            AircraftType = "Boeing 737-800",
                            AirlineId = 15,
                            ArrivalTime = new TimeSpan(0, 10, 45, 0, 0),
                            CabinType = "Economy Plus",
                            Date = new DateTime(2026, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 6, 0, 0, 0),
                            Emission = 350.89999999999998,
                            FlightCode = "SY880",
                            From = "Minneapolis",
                            Price = 520.00m,
                            To = "Cancun"
                        },
                        new
                        {
                            FlightId = 6,
                            AircraftType = "ATR 72",
                            AirlineId = 16,
                            ArrivalTime = new TimeSpan(0, 10, 25, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 9, 10, 0, 0),
                            Emission = 90.599999999999994,
                            FlightCode = "TR222",
                            From = "Tampa",
                            Price = 130.00m,
                            To = "Key West"
                        });
                });

            modelBuilder.Entity("Group3Flight.Models.FlightReservations", b =>
                {
                    b.Property<int>("FlightReservationsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FlightId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FlightReservationsId");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightReservations");
                });

            modelBuilder.Entity("Group3Flight.Models.Flight", b =>
                {
                    b.HasOne("Group3Flight.Models.Airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Group3Flight.Models.FlightReservations", b =>
                {
                    b.HasOne("Group3Flight.Models.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });
#pragma warning restore 612, 618
        }
    }
}
